## Taken from one of my other repos: https://github.com/mkiang/modeling_reemergence/blob/5d048d39f9bfd369f2744fe081daf7104f5d021d/code/utils.R#L1174

return_st_info <- function() {
    structure(
        list(
            abbrev = c(
                "AK",
                "AL",
                "AR",
                "AZ",
                "CA",
                "CO",
                "CT",
                "DC",
                "DE",
                "FL",
                "GA",
                "HI",
                "IA",
                "ID",
                "IL",
                "IN",
                "KS",
                "KY",
                "LA",
                "MA",
                "MD",
                "ME",
                "MI",
                "MN",
                "MO",
                "MS",
                "MT",
                "NC",
                "ND",
                "NE",
                "NH",
                "NJ",
                "NM",
                "NV",
                "NY",
                "OH",
                "OK",
                "OR",
                "PA",
                "RI",
                "SC",
                "SD",
                "TN",
                "TX",
                "US",
                "UT",
                "VA",
                "VT",
                "WA",
                "WI",
                "WV",
                "WY",
                NA
            ),
            division = c(
                "Pacific",
                "East South Central",
                "West South Central",
                "Mountain",
                "Pacific",
                "Mountain",
                "New England",
                "South Atlantic",
                "South Atlantic",
                "South Atlantic",
                "South Atlantic",
                "Pacific",
                "West North Central",
                "Mountain",
                "East North Central",
                "East North Central",
                "West North Central",
                "East South Central",
                "West South Central",
                "New England",
                "South Atlantic",
                "New England",
                "East North Central",
                "West North Central",
                "West North Central",
                "East South Central",
                "Mountain",
                "South Atlantic",
                "West North Central",
                "West North Central",
                "New England",
                "Middle Atlantic",
                "Mountain",
                "Mountain",
                "Middle Atlantic",
                "East North Central",
                "West South Central",
                "Pacific",
                "Middle Atlantic",
                "New England",
                "South Atlantic",
                "West North Central",
                "East South Central",
                "West South Central",
                "Whole US",
                "Mountain",
                "South Atlantic",
                "New England",
                "Pacific",
                "East North Central",
                "South Atlantic",
                "Mountain",
                "Unknown"
            ),
            st_lat = c(
                49.25,
                32.5901,
                34.7336,
                34.2192,
                36.5341,
                38.6777,
                41.5928,
                38.9072,
                38.6777,
                27.8744,
                32.3329,
                31.75,
                41.9358,
                43.5648,
                40.0495,
                40.0495,
                38.4204,
                37.3915,
                30.6181,
                42.3645,
                39.2778,
                45.6226,
                43.1361,
                46.3943,
                38.3347,
                32.6758,
                46.823,
                35.4195,
                47.2517,
                41.3356,
                43.3934,
                39.9637,
                34.4764,
                39.1063,
                43.1361,
                40.221,
                35.5053,
                43.9078,
                40.9069,
                41.5928,
                33.619,
                44.3365,
                35.6767,
                31.3897,
                0,
                39.1063,
                37.563,
                44.2508,
                47.4231,
                44.5937,
                38.4204,
                43.0504,
                0
            ),
            st_lon = c(
                -127.25,
                -86.7509,
                -92.2992,
                -111.625,
                -119.773,
                -105.513,
                -72.3573,
                -77.0369,
                -74.9841,
                -81.685,
                -83.3736,
                -126.25,
                -93.3714,
                -113.93,
                -89.3776,
                -86.0808,
                -98.1156,
                -84.7674,
                -92.2724,
                -71.58,
                -76.6459,
                -68.9801,
                -84.687,
                -94.6043,
                -92.5137,
                -89.8065,
                -109.32,
                -78.4686,
                -100.099,
                -99.5898,
                -71.3924,
                -74.2336,
                -105.942,
                -116.851,
                -75.1449,
                -82.5963,
                -97.1239,
                -120.068,
                -77.45,
                -71.1244,
                -80.5056,
                -99.7238,
                -86.456,
                -98.7857,
                200,
                -111.33,
                -78.2005,
                -72.545,
                -119.746,
                -89.9941,
                -80.6665,
                -107.256,
                199
            ),
            name = c(
                "Alaska",
                "Alabama",
                "Arkansas",
                "Arizona",
                "California",
                "Colorado",
                "Connecticut",
                "District of Columbia",
                "Delaware",
                "Florida",
                "Georgia",
                "Hawaii",
                "Iowa",
                "Idaho",
                "Illinois",
                "Indiana",
                "Kansas",
                "Kentucky",
                "Louisiana",
                "Massachusetts",
                "Maryland",
                "Maine",
                "Michigan",
                "Minnesota",
                "Missouri",
                "Mississippi",
                "Montana",
                "North Carolina",
                "North Dakota",
                "Nebraska",
                "New Hampshire",
                "New Jersey",
                "New Mexico",
                "Nevada",
                "New York",
                "Ohio",
                "Oklahoma",
                "Oregon",
                "Pennsylvania",
                "Rhode Island",
                "South Carolina",
                "South Dakota",
                "Tennessee",
                "Texas",
                "Whole US",
                "Utah",
                "Virginia",
                "Vermont",
                "Washington",
                "Wisconsin",
                "West Virginia",
                "Wyoming",
                "Unknown State"
            ),
            st_fips = c(
                "02",
                "01",
                "05",
                "04",
                "06",
                "08",
                "09",
                "11",
                "10",
                "12",
                "13",
                "15",
                "19",
                "16",
                "17",
                "18",
                "20",
                "21",
                "22",
                "25",
                "24",
                "23",
                "26",
                "27",
                "29",
                "28",
                "30",
                "37",
                "38",
                "31",
                "33",
                "34",
                "35",
                "32",
                "36",
                "39",
                "40",
                "41",
                "42",
                "44",
                "45",
                "46",
                "47",
                "48",
                "999",
                "49",
                "51",
                "50",
                "53",
                "55",
                "54",
                "56",
                NA
            ),
            lon_rank = c(
                1L,
                28L,
                23L,
                8L,
                4L,
                13L,
                47L,
                41L,
                44L,
                35L,
                33L,
                2L,
                21L,
                7L,
                27L,
                30L,
                18L,
                31L,
                24L,
                48L,
                42L,
                51L,
                32L,
                20L,
                22L,
                26L,
                10L,
                38L,
                14L,
                16L,
                49L,
                45L,
                12L,
                6L,
                43L,
                34L,
                19L,
                3L,
                40L,
                50L,
                37L,
                15L,
                29L,
                17L,
                53L,
                9L,
                39L,
                46L,
                5L,
                25L,
                36L,
                11L,
                52L
            ),
            alpha_rank = c(
                2L,
                1L,
                4L,
                3L,
                5L,
                6L,
                7L,
                9L,
                8L,
                10L,
                11L,
                12L,
                16L,
                13L,
                14L,
                15L,
                17L,
                18L,
                19L,
                22L,
                21L,
                20L,
                23L,
                24L,
                26L,
                25L,
                27L,
                34L,
                35L,
                28L,
                30L,
                31L,
                32L,
                29L,
                33L,
                36L,
                37L,
                38L,
                39L,
                40L,
                41L,
                42L,
                43L,
                44L,
                52L,
                45L,
                47L,
                46L,
                48L,
                50L,
                49L,
                51L,
                53L
            ),
            st_cat = structure(
                c(
                    1L,
                    28L,
                    23L,
                    8L,
                    4L,
                    13L,
                    47L,
                    41L,
                    44L,
                    35L,
                    33L,
                    2L,
                    21L,
                    7L,
                    27L,
                    30L,
                    18L,
                    31L,
                    24L,
                    48L,
                    42L,
                    51L,
                    32L,
                    20L,
                    22L,
                    26L,
                    10L,
                    38L,
                    14L,
                    16L,
                    49L,
                    45L,
                    12L,
                    6L,
                    43L,
                    34L,
                    19L,
                    3L,
                    40L,
                    50L,
                    37L,
                    15L,
                    29L,
                    17L,
                    52L,
                    9L,
                    39L,
                    46L,
                    5L,
                    25L,
                    36L,
                    11L,
                    NA
                ),
                levels = c(
                    "AK",
                    "HI",
                    "OR",
                    "CA",
                    "WA",
                    "NV",
                    "ID",
                    "AZ",
                    "UT",
                    "MT",
                    "WY",
                    "NM",
                    "CO",
                    "ND",
                    "SD",
                    "NE",
                    "TX",
                    "KS",
                    "OK",
                    "MN",
                    "IA",
                    "MO",
                    "AR",
                    "LA",
                    "WI",
                    "MS",
                    "IL",
                    "AL",
                    "TN",
                    "IN",
                    "KY",
                    "MI",
                    "GA",
                    "OH",
                    "FL",
                    "WV",
                    "SC",
                    "NC",
                    "VA",
                    "PA",
                    "DC",
                    "MD",
                    "NY",
                    "DE",
                    "NJ",
                    "VT",
                    "CT",
                    "MA",
                    "NH",
                    "RI",
                    "ME",
                    "US"
                ),
                class = c(
                    "ordered",
                    "factor"
                )
            ),
            name_cat = structure(
                c(
                    2L,
                    1L,
                    4L,
                    3L,
                    5L,
                    6L,
                    7L,
                    9L,
                    8L,
                    10L,
                    11L,
                    12L,
                    16L,
                    13L,
                    14L,
                    15L,
                    17L,
                    18L,
                    19L,
                    22L,
                    21L,
                    20L,
                    23L,
                    24L,
                    26L,
                    25L,
                    27L,
                    34L,
                    35L,
                    28L,
                    30L,
                    31L,
                    32L,
                    29L,
                    33L,
                    36L,
                    37L,
                    38L,
                    39L,
                    40L,
                    41L,
                    42L,
                    43L,
                    44L,
                    51L,
                    46L,
                    48L,
                    47L,
                    49L,
                    52L,
                    50L,
                    53L,
                    45L
                ),
                levels = c(
                    "Alabama",
                    "Alaska",
                    "Arizona",
                    "Arkansas",
                    "California",
                    "Colorado",
                    "Connecticut",
                    "Delaware",
                    "District of Columbia",
                    "Florida",
                    "Georgia",
                    "Hawaii",
                    "Idaho",
                    "Illinois",
                    "Indiana",
                    "Iowa",
                    "Kansas",
                    "Kentucky",
                    "Louisiana",
                    "Maine",
                    "Maryland",
                    "Massachusetts",
                    "Michigan",
                    "Minnesota",
                    "Mississippi",
                    "Missouri",
                    "Montana",
                    "Nebraska",
                    "Nevada",
                    "New Hampshire",
                    "New Jersey",
                    "New Mexico",
                    "New York",
                    "North Carolina",
                    "North Dakota",
                    "Ohio",
                    "Oklahoma",
                    "Oregon",
                    "Pennsylvania",
                    "Rhode Island",
                    "South Carolina",
                    "South Dakota",
                    "Tennessee",
                    "Texas",
                    "Unknown State",
                    "Utah",
                    "Vermont",
                    "Virginia",
                    "Washington",
                    "West Virginia",
                    "Whole US",
                    "Wisconsin",
                    "Wyoming"
                ),
                class = c("ordered", "factor")
            ),
            name_cat_alpha = structure(
                c(
                    2L,
                    1L,
                    4L,
                    3L,
                    5L,
                    6L,
                    7L,
                    9L,
                    8L,
                    10L,
                    11L,
                    12L,
                    16L,
                    13L,
                    14L,
                    15L,
                    17L,
                    18L,
                    19L,
                    22L,
                    21L,
                    20L,
                    23L,
                    24L,
                    26L,
                    25L,
                    27L,
                    34L,
                    35L,
                    28L,
                    30L,
                    31L,
                    32L,
                    29L,
                    33L,
                    36L,
                    37L,
                    38L,
                    39L,
                    40L,
                    41L,
                    42L,
                    43L,
                    44L,
                    52L,
                    45L,
                    47L,
                    46L,
                    48L,
                    50L,
                    49L,
                    51L,
                    53L
                ),
                levels = c(
                    "Alabama",
                    "Alaska",
                    "Arizona",
                    "Arkansas",
                    "California",
                    "Colorado",
                    "Connecticut",
                    "Delaware",
                    "District of Columbia",
                    "Florida",
                    "Georgia",
                    "Hawaii",
                    "Idaho",
                    "Illinois",
                    "Indiana",
                    "Iowa",
                    "Kansas",
                    "Kentucky",
                    "Louisiana",
                    "Maine",
                    "Maryland",
                    "Massachusetts",
                    "Michigan",
                    "Minnesota",
                    "Mississippi",
                    "Missouri",
                    "Montana",
                    "Nebraska",
                    "Nevada",
                    "New Hampshire",
                    "New Jersey",
                    "New Mexico",
                    "New York",
                    "North Carolina",
                    "North Dakota",
                    "Ohio",
                    "Oklahoma",
                    "Oregon",
                    "Pennsylvania",
                    "Rhode Island",
                    "South Carolina",
                    "South Dakota",
                    "Tennessee",
                    "Texas",
                    "Utah",
                    "Vermont",
                    "Virginia",
                    "Washington",
                    "West Virginia",
                    "Wisconsin",
                    "Wyoming",
                    "Whole US",
                    "Unknown State"
                ),
                class = c("ordered", "factor")
            )
        ),
        row.names = c(NA, -53L),
        class = c(
            "tbl_df",
            "tbl", "data.frame"
        )
    )
}
