---
title: "UCOD vs Record1"
author: "Mathew Kiang"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r, results='hide'}
library(arrow)
library(tidyverse)
library(here)
library(fs)
library(usmap)
```

```{r}
f_list <- dir_ls(here("data_private", "mcod"), glob = "*.parquet")

holder <- vector("list", NROW(f_list))

for (i in 1:NROW(f_list)) {
    temp_x <- read_parquet(f_list[i]) |> 
        select(year, county_ihme, ucod, record_1)
    
    temp_x <- bind_rows(
        temp_x,
        temp_x |> 
            mutate(county_ihme = "USA")
    )
    
    holder[[i]] <- temp_x |> 
        group_by(county_ihme, year) |> 
        summarize(n_distinct_ucod = n_distinct(ucod),
                  n_distinct_r1 = n_distinct(record_1),
                  n_total_deaths = n(),
                  n_same_ucod_r1 = sum(ucod == record_1),
                  n_diff_ucod_r1 = sum(ucod != record_1), 
                  n_missing_ucod = sum(is.na(ucod)),
                  n_missing_r1 = sum(is.na(record_1))) |> 
        mutate(prop_same_ucod_r1 = n_same_ucod_r1 / n_total_deaths,
               prop_diff_ucod_r1 = n_diff_ucod_r1 / n_total_deaths) |> 
        arrange(desc(prop_diff_ucod_r1))
}
```

```{r}
holder <- holder |> 
    bind_rows() |> 
    ungroup()
```

## County-year 
```{r fig.height=15, fig.width=6}
ggplot(holder,
       aes(x = year, y = county_ihme, fill = prop_diff_ucod_r1)) + 
    geom_tile() + 
    scale_fill_viridis_c() + 
    theme(axis.text.y = element_blank(),
          axis.title.y = element_blank())
```


## Spatial distribution

```{r}
sub_df <- holder |> 
    filter(year <= 2005,
           county_ihme != "USA") |> 
    left_join(usmap::us_map("counties") |> 
                  select(county_ihme = fips, geom))
```

```{r fig.height=14, fig.width=16}
ggplot(sub_df, aes(fill = prop_diff_ucod_r1)) + 
    geom_sf(aes(geometry = geom), color = "white") + 
    scale_fill_viridis_c() +
    facet_wrap(~ year) + 
    theme_void() + 
    theme(legend.position = c(.9, 0),
          legend.justification = c(1, 0))
```

## Save

Save with shuffled (but time-consistent) geography

```{r}
mapping_df <- holder |> 
    select(county_ihme) |>
    distinct()|> 
    ungroup() |> 
    mutate(county_shuffled = sample(county_ihme))

holder <- holder |> 
    left_join(mapping_df) |> 
    select(-county_ihme)

saveRDS(holder, here("data", "ucod_vs_record1.RDS"), compress = "xz")
```

